### ISSUE TITLE
Design us a nice Hugo website for the project

### ISSUE THREAD

**Issue by mickfuzz** [glitch-game-club/glitch-game-club#30]
We would love to use this repository and Hugo as our main blogging and documentation platform.

 We also want our web presence to be as inspirational as the contents of the club.

So we are looking for a Web Dev/ Designer to create;

- a Hugo site
- a base page with a list of our games and how to get involved
- a blogging template 

Could this be you? Please comment to ask questions or volunteer.

**Comment by GeysaPriscila** [comment]
Is it to start the website from scratch?

**Comment by dtDee123** [comment]
Yeah!I definitely wanna be part of.

**Comment by mickfuzz** [comment]
I'll get a fuller spec together. 

It's to be a more graphical, bloggy front end to this project. 
The project is to work from scratch. But there is an existing project blog that would be replaced. So there is some content to draw on. http://digitalducks.org/webgames-club/
Graphical style hashtags would be  #fun, #techy, #crafty, #maker, #retrogames

What info / resources? Would be helpful?

**Comment by Ameranthi** [comment]
I would like to try making a blog template. I may not be able to do the whole task alone but I think I can make something cool.

**Comment by rundaskill** [comment]
I would like to participate. the first thing is to do the mockups

**Comment by ruchit2801** [comment]
I can work on base page, has anyone worked on it yet?

**Comment by mkiara** [comment]
I would like to participate too. Agreed that we shall need mockup for this. @ruchit2801 I think no one have start, am I right sir @mickfuzz ?

> I would like to try making a blog template. I may not be able to do the whole task alone but I think I can make something cool.

**Comment by larry-cherry** [comment]
This looks like fun. What tasks still need to be accomplished. Do I need to pick an issue and make a pull request or get a task assigned?

**Comment by mickfuzz** [comment]
Thanks for your patience everyone. 

It's been a busy week at work and getting ready to do a fun day playing and making games and Manchester Central library this weekend!

I'm overwhelmed at the offers of help that's great!

I don't have a lot of experience in coordinating git projects and I would like to try to balance getting a few people involved and not annoying you by getting to may involved. To get the ball rolling I'll lbreak down a few jobs here but feel free to guide me in other things that are needed. 

First up, if anyone wants to take on a role in co-coordinating this project, I've created an issue #45 - jump on that an I'll assign you. 

Second up, can you help convert Key pages of http://digitalducks.org/webgames-club/ to Mark Down for Hugo #46 I'll work with you on this to get the info updated too. 

Then, what about create site structure in Hugo as per - #47

And finally, could anyone create or adapt a hugo theme suitable to the project #48

I hope this is helpful. Let's all jump in and do what we can and just chime in if you have comments about how best to approach it.

**Comment by mickfuzz** [comment]
@GeysaPriscila @Ameranthi @rundaskill @ruchit2801 @larry-cherry @mkiara 

I've started the process via this commit 
5ca8f2e516d068de25eb32e9f3e954117e1b0f41
It would be great if you could have a look at the issues #45 #46 #47 #48  and see if you can help out. 

Many Thanks! Mick
