### ISSUE TITLE
Create a code template for show casing Game Mechanics

### ISSUE THREAD

**Issue by mickfuzz** [glitch-game-club/glitch-game-club#37]
As per this great site - http://gamemechanicexplorer.com/

Let's create a simpler one.

**Comment by larry-cherry** [comment]
This looks like fun. What tasks still need to be accomplished. Do I need to pick an issue and make a pull request or get a task assigned?

**Comment by mickfuzz** [comment]
I think the examples above are good. 
They need to be linted as per CODE_GUIDE.md 

Then I suggest doing one of:

- creating one Git repo called Game Mechanics with different html files and embedded code and importing that into Glitch
- creating one glitch project per game mechanic and creating a separate web page / wiki page site listing them

Perhaps do the former first as it's quicker, the disadvantage is the presence of the surrounding HTML for beginner users, but that could be a minor thing in the end.

**Comment by mickfuzz** [comment]
This resolved by this page 

https://ggc-examples.glitch.me/
